# Generated by Django 5.1.2 on 2025-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='daily_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('meal_date', models.DateField()),
                ('meal_selected', models.CharField(max_length=100)),
                ('meal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras_taken', models.TextField()),
                ('extras_quantities', models.TextField()),
                ('extras_total_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExtraName', models.CharField(max_length=50)),
                ('ExtraPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MealOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MealName', models.CharField(max_length=50)),
                ('MealPrice', models.IntegerField()),
            ],
        ),
    ]
