# Generated by Django 5.1.2 on 2025-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='number',
            field=models.IntegerField(max_length=11),
        ),
    ]
