# Generated by Django 5.1.2 on 2025-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffinmanagement', '0003_alter_customers_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
